print("Aammar")
print(2+3)
print("we are learning in codnaics platform")
print ("this is first program")
print(5*2)
print(5-2)
print(9/3)
print("this is 2nd program")
print("this is 3rd program")
print("this is 4th program")
print("this is 5th program")

print(58/(4*5)+3**2)